// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	storage "analiticsURLShortener/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// URLAnalyticsGetter is an autogenerated mock type for the URLAnalyticsGetter type
type URLAnalyticsGetter struct {
	mock.Mock
}

// GetAnalytics provides a mock function with given fields: alias
func (_m *URLAnalyticsGetter) GetAnalytics(alias string) (storage.AnalyticsData, error) {
	ret := _m.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 storage.AnalyticsData
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (storage.AnalyticsData, error)); ok {
		return rf(alias)
	}
	if rf, ok := ret.Get(0).(func(string) storage.AnalyticsData); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Get(0).(storage.AnalyticsData)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLAnalyticsGetter creates a new instance of URLAnalyticsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLAnalyticsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLAnalyticsGetter {
	mock := &URLAnalyticsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
